### ISSUE TITLE
Crashes if PSF is not specified

### ISSUE THREAD

**Issue by sphemakh** [SpheMakh/sourcery#1]
I get an error when I run this without a PSF. This is a problem since the PSF should be optional. This is the error message:

```
Traceback (most recent call last):
  File "/usr/local/bin/sourcery", line 5, in <module>
    main()
  File "/usr/local/lib/python2.7/dist-packages/Sourcery/main.py", line 251, in main
    psfs = args.psf.split(",")
AttributeError: 'NoneType' object has no attribute 'split'
```

**Comment by sphemakh** [comment]
@Sebokolodi  I've added a quick workaround. But its probably not the best way to do this.
